// fontawesome.js
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// 导入你需要的图标
import { 
  faHome, 
  faUser, 
  faSignInAlt, 
  faSignOutAlt,
  faEdit,
  faTrash,
  faPlus,
  faList,
  faSearch,
  faTag,
  faTags,
  faFolder,
  faThLarge,
  faThumbsUp,
  faComment,
  faEye,
  faClock,
  faHeart,
  faShare,
  faSave,
  faUndo,
  faRedo,
  faImage,
  faLink,
  faCode,
  faBold,
  faItalic,
  faHeading,
  faQuoteRight,
  faListUl,
  faListOl,
  faTasks,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faExclamationTriangle,
  faCheck,
  faTimes,
  faInfoCircle,
  faBell,
  faUserPlus,
  faLock,
  faEnvelope,
  faEye as faEyeSolid,
  faEyeSlash,
  faSpinner,
  faFlag,
  faPhone,
  faIdBadge,
  faQuestionCircle,
  faCog
} from '@fortawesome/free-solid-svg-icons'

import {
  faHeart as farHeart,
  faComment as farComment,
  faUser as farUser,
  faBell as farBell,
  faEye as farEye
} from '@fortawesome/free-regular-svg-icons'

import {
  faGithub,
  faTwitter,
  faFacebook,
  faLinkedin,
  faWeibo,
  faWeixin,
  faGoogle
} from '@fortawesome/free-brands-svg-icons'

// 添加图标到库
library.add(
  faHome, 
  faUser, 
  faSignInAlt, 
  faSignOutAlt,
  faEdit,
  faTrash,
  faPlus,
  faList,
  faSearch,
  faTag,
  faTags,
  faFolder,
  faThLarge,
  faThumbsUp,
  faComment,
  faEye,
  faClock,
  faHeart,
  faShare,
  faSave,
  faUndo,
  faRedo,
  faImage,
  faLink,
  faCode,
  faBold,
  faItalic,
  faHeading,
  faQuoteRight,
  faListUl,
  faListOl,
  faTasks,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faExclamationTriangle,
  faCheck,
  faTimes,
  faInfoCircle,
  faBell,
  faUserPlus,
  faLock,
  faEnvelope,
  faEyeSolid,
  faEyeSlash,
  faSpinner,
  faFlag,
  faPhone,
  faIdBadge,
  faQuestionCircle,
  faCog,
  // Regular icons
  farHeart,
  farComment,
  farUser,
  farBell,
  farEye,
  // Brand icons
  faGithub,
  faTwitter,
  faFacebook,
  faLinkedin,
  faWeibo,
  faWeixin,
  faGoogle
)

export { FontAwesomeIcon } 